server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    exchange: order-exchange
    order:
      name: order-queue
      routing-key: order-routing-key
    email:
      name: order-email-queue
      routing-key: order-email-routing-key

logging:
  level:
    com.vedha.order: DEBUG

management:
  health:
    rabbit:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: ${spring.application.name}
    description: Order Service RabbitMQ Producer
    environment: ${spring.profiles.active}
    version: '@project.version@'